"""Compile concepts/*.json back into a single master text export.

The JSON files are the source of truth; this export is generated, never
edited by hand.
"""
import json
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONCEPTS_DIR = ROOT / "concepts"
EXPORTS_DIR = ROOT / "exports"


def load_entries():
    entries = []
    for path in sorted(CONCEPTS_DIR.glob("*.json")):
        entries.extend(json.loads(path.read_text(encoding="utf-8")))
    entries.sort(key=lambda e: e.get("master_index", 0))
    return entries


def main():
    entries = load_entries()
    assert entries, "no concept files found"
    ids = [e["id"] for e in entries]
    assert len(set(ids)) == len(ids), "duplicate ids across domains"
    names = [e["name"].lower() for e in entries]
    assert len(set(names)) == len(names), "duplicate names across domains"

    EXPORTS_DIR.mkdir(exist_ok=True)
    out = EXPORTS_DIR / "master_v2.txt"
    with out.open("w", encoding="utf-8") as f:
        f.write("PAKUPAI TRADING KNOWLEDGE LIBRARY — MASTER EXPORT (v2)\n")
        f.write(f"Generated: {date.today().isoformat()} from concepts/*.json\n")
        f.write("Encoding: UTF-8\n\n")
        f.write(f"Total entries: {len(entries)}\n")
        f.write(f"Total citations: {sum(len(e.get('citations', [])) for e in entries)}\n\n")
        f.write("This file is generated by scripts/export_master.py.\n")
        f.write("Do not edit by hand; edit the concept JSON files instead.\n\n")
        f.write("=" * 60 + "\nENTRIES\n" + "=" * 60 + "\n")
        for i, e in enumerate(entries, 1):
            f.write(f"\n{i:04d}. {e['name']}\n")
            f.write(f"Domain: {e['domain']}\n")
            f.write(f"Definition: {e['definition']}\n")
            if e.get("intuition"):
                f.write(f"Intuition: {e['intuition']}\n")
            if e.get("mechanics"):
                f.write(f"Mechanics: {e['mechanics']}\n")
            if e.get("formula"):
                f.write(f"Formula: {e['formula']}\n")
            if e.get("relationships"):
                f.write(f"Relationships: {', '.join(e['relationships'])}\n")
            if e.get("failure_modes"):
                f.write(f"Failure modes: {e['failure_modes']}\n")
            if e.get("misconceptions"):
                f.write(f"Misconceptions: {e['misconceptions']}\n")
            if e.get("example"):
                f.write(f"Example: {e['example']}\n")
            if e.get("citations"):
                for c in e["citations"]:
                    f.write(f"Citation: {c.get('source', '')} — {c.get('url', '')}"
                            f" ({c.get('section', '')})\n")
        f.write("\n" + "=" * 60 + "\nEND OF MASTER\n")

    print(f"exported {len(entries)} entries to {out.name}")
    print(f"citations: {sum(len(e.get('citations', [])) for e in entries)}")


if __name__ == "__main__":
    sys.exit(main())
